#!/bin/bash

# Exit build script on first failure.
set -e

# Exit on unset variable.
set -u

is_litestream_enabled() {
  set +ux

  local IS_ENABLED='false'

  if [[ ! -z "${LITESTREAM_ACCESS_KEY_ID}" ]] && \
      [[ ! -z "${LITESTREAM_SECRET_ACCESS_KEY}" ]]; then
    IS_ENABLED='true';
  fi

  set -ux

  echo "${IS_ENABLED}"
}

readonly IS_LITESTREAM_ENABLED="$(is_litestream_enabled)"

# Echo commands to stdout.
set -x

if [[ "${IS_LITESTREAM_ENABLED}" == 'true' ]]; then

    export readonly DB_PATH="/data/nodered.db"

    # Restore database from S3.
    /usr/src/node-red/litestream restore -if-replica-exists -if-db-not-exists -v "${DB_PATH}"

    # Let Litestream start LogPaste as a child process
    /usr/src/node-red/litestream replicate \
        -exec "/usr/local/bin/node node_modules/node-red/red.js --userDir /data"
        "${DB_PATH}" \
        "${DB_REPLICA_URL}"
else
    # Start server.
    eval "/usr/local/bin/node node_modules/node-red/red.js --userDir /data"
fi