# fly.toml app configuration file generated for nodered-server on 2023-04-23T09:17:44+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "nodered-server"
primary_region = "sin"

[http_service]
  internal_port = 1880
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  [http_service.concurrency]
    type = "requests"
    soft_limit = 200
    hard_limit = 250

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
